- name: install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - "{{ install_location }}"
    - "{{ out_dir }}"
  become_user: "{{ ansible_user }}"

- name: Get installation files
  get_url:
    url: "{{ binary_url }}/cockroach-{{ CDB_SNAPSHOT }}.linux-amd64.tgz"
    dest: "/tmp/cockroach-{{ CDB_SNAPSHOT }}.linux-amd64.tgz"
    validate_certs: false

- name: Unpack/install binaries
  unarchive:
    src: "/tmp/cockroach-{{ CDB_SNAPSHOT }}.linux-amd64.tgz"
    dest: "{{ install_location }}"
    copy: no

- name: create symlink to /usr/local/bin
  file:
    src: "{{ install_location }}/cockroach-{{ CDB_SNAPSHOT }}.linux-amd64/cockroach"
    dest: /usr/local/bin/cockroach
    state: link

  become: true
- name: setup haproxy
  shell: |
    cockroach gen haproxy --insecure --host="{{ groups['all'][0] }}" --port=26257
    mv haproxy.cfg {{ out_dir }}
    sed -i -r 's/26257/{{ haproxy_port }}/g' {{ out_dir }}/haproxy.cfg
    haproxy -f {{ out_dir }}/haproxy.cfg > {{ out_dir }}/haproxy.log 2>&1 & sleep 1