#host-setup props-----------------------------------------
ansible_user: centos
packages_centos:
  - tzdata
#install-cockroach props-------------------------------------------------
device_name: /dev/xvdb
cloud_type: aws
mount_path: /mnt/d0

data_dir: "{{ mount_path }}/cockroach/data"
out_dir: "{{ mount_path }}/cockroach/conf"
binary_url: https://binaries.cockroachdb.com
CDB_SNAPSHOT: v22.2.3
install_location: "{{ mount_path }}/install/cockroach"
haproxy_port: 26257
chaos_time: 60
wait_time: 1

ulimits_security:
  - { limit_type: '-', limit_item: 'core', value: unlimited }
  - { limit_type: '-', limit_item: 'nofile', value: 1048576 }
  - { limit_type: '-', limit_item: 'nproc', value: 40000 }
